---
-
  name: Update Kaly Chain binary
  hosts:
    - all
  become: yes
  tasks:
    ## update & upgrade system
    - name: Update & upgrade system
      apt:
        upgrade: yes
        update_cache: yes

    ## stop kalychain service
    - name: Stop kaly chain service
      systemd:
        state: stopped
        name: kalychain

    ## get the latest release
    - name: Get latest release link
      uri:
        url: https://api.github.com/repos/KalyCoinProject/kalychain/releases/latest
        return_content: true
      register: edge_release

    ## download the latest release
    - name: Download latest Kaly Chain release
      get_url:
        url: "{{ edge_release.json.assets[3].browser_download_url }}"
        dest: /tmp/kalychain.tar.gz
        force: yes

    ## create temp dir for release
    - name: Create temp dir for Kaly Chain release
      file:
        path: /tmp/kalychain
        state: directory

    ## unpack release tar
    - name: Unpack Kaly Chain release
      unarchive:
        remote_src: yes
        src: /tmp/kalychain.tar.gz
        dest: /tmp/kalychain

    ## set kalychain to PATH
    - name: Place Kaly Chain binary to PATH
      copy:
        remote_src: yes
        src: /tmp/kalychain/kalychain
        dest: /usr/local/bin/
        mode: a+x
        force: yes

    ## remove release temp dir
    - name: Remove temp Kaly Chain release dir
      file:
        state: absent
        path: /tmp/kalychain

    ## start kaly chain service
    - name: Start kalychain service
      systemd:
        state: restarted
        name: kalychain
        daemon_reload: yes
        enabled: yes